---
name: Check Markdown Links
on:
  push:
    branches:
      - vk-test
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'
  schedule:
  # Run everyday at 9:00 AM (See https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07)
  - cron: "0 9 * * *"
  repository_dispatch: # run manually
    types: [check-link]
env:
  DISABLE_TELEMETRY: 1
jobs:
  markdown-link-check:
    name: Broken Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'
          check-modified-files-only: 'yes'
          config-file: .github/workflows/markdown-links-config.json